### ISSUE TITLE
Communicate with main app

### ISSUE THREAD

**Issue by zecar** [KABBOUCHI/adonisjs-scheduler#6]
This is more of a request for help, than an issue

I have the main app running with a socket.io server opened using this guide: https://v5-docs.adonisjs.com/cookbooks/socketio-with-adonisjs

Inside the scheduler, I need to notify the socket.io server in order to emit events to the clients connected to the main app.

Does anyone know any way I can do that? How can I communicate with the running adonis server from within the scheduler

**Comment by KABBOUCHI** [comment]
u need to use https://socket.io/docs/v4/redis-streams-adapter
