### ISSUE TITLE
Using with Docker

### ISSUE THREAD

**Issue by trulysinclair** [KABBOUCHI/adonisjs-scheduler#9]
I have my application server running in docker, how could I run the scheduler as well? I know the PM2 setup on a server but with Docker I don't know how to run both the server and the scheduler unless I were to have two Dockerfiles for the same server with one running `serve` and the other running `scheduler:run`, but would this cause any problems?

**Comment by KABBOUCHI** [comment]
assuming ur docker file ends like this, which run a normal adonis web/api instance

```Dockerfile
CMD [ "npm", "run", "start" ]
```

for scheduler u run the same image but override the command with

```sh
node ace scheduler:run
```

probably something like this
```sh
docker run my-adonis-image -c 'node ace scheduler:run'
```

**Comment by trulysinclair** [comment]
Thank you, @KABBOUCHI!
